resources:
- repo: self
  clean: true

jobs:
- job: 'Build test result'

  steps:

  - bash: |
    # pytest --junitxml=junit.xml

    displayName: Pytest

  - task: PublishTestResults@2
    displayName: 'Publish Test Results'
    inputs:
      testResultsFiles: '*.xml'



